apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      initContainers:
      - name: check-db
        image: busybox
        command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for database; sleep 2; done;']

      containers:
      - name: login-app
        image: login-app-kub:latest 
        imagePullPolicy: Never 

        ports:
        - containerPort: 5000

        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:mypassword@db:5432/mydatabase"
